# Generated by Django 4.1.3 on 2022-11-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40, unique=True)),
                ('email', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('perfil', models.IntegerField()),
            ],
        ),
    ]
